[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
select = ["E","F","I","UP","B","PL"]
ignore = ["E203","E501","B008"]

[tool.pytest.ini_options]
addopts = "-q"
pythonpath = ["."]
testpaths = ["app/tests"]
